### ISSUE TITLE
[BUG]使用model_zoo里训练resnet时，报错RuntimeError: Unexpected error. Failed to open file: ./WHU-RS19/Parking/parking_28.jpg

### ISSUE THREAD

**Issue by cherishhh** [WHULuoJiaTeam/luojianet#16]
============== Starting Training ==============
[WARNING] ME(19208:139772197278208,MainProcess):2022-10-27-18:32:37.851.63 [luojianet_ms/train/model.py:573] The CPU cannot support dataset sink mode currently.So the training process will be performed with dataset not sink.
[WARNING] DEBUG(19208,7f1f402b1200,python):2022-10-27-18:32:37.123.286 [luojianet_ms/ccsrc/debug/debugger/debugger.cc:96] Debugger] Not enabling debugger. Debugger does not support CPU.
[ERROR] MD(19208,7f1e8fbba700,python):2022-10-27-18:32:37.156.100 [luojianet_ms/ccsrc/minddata/dataset/util/task_manager.cc:219] InterruptMaster] Task is terminated with err msg(more detail in info level log):Unexpected error. Failed to open file: ./WHU-RS19/Parking/parking_28.jpg
Line of code : 277
File         : /home/vhr/tll/download/luojianet/luojianet_ms/ccsrc/minddata/dataset/core/tensor.cc

[WARNING] ME(19709:140164741772224,MainProcess):2022-10-27-18:32:38.345.906 [luojianet_ms/common/_decorator.py:34] 'DropoutDoMask' is deprecated from version 1.5 and will be removed in a future version, use 'ops.Dropout' instead.
The new bprop mindir files has been generated in the path "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/ops/_grad/../bprop_mindir", copy the *.mindir to your luojianet_ms path or PYTHONPATH if necessary.
epoch: 1 step: 1, loss is 2.9637277126312256
Traceback (most recent call last):
  File "/home/y00572966/luojianet_test/luojianet/model_zoo/rs_scene_classification/ResNet/train.py", line 77, in <module>
    model.train(config.epoch_size, dataset, callbacks=[time_cb,ckpoint_cb,LossMonitor()])
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/train/model.py", line 808, in train
    self._train(epoch,
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/train/model.py", line 112, in wrapper
    func(self, *args, **kwargs)
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/train/model.py", line 575, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params)
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/train/model.py", line 693, in _train_process
    for next_element in dataset_helper:
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/train/dataset_helper.py", line 523, in __next__
    data = self.iter.__next__()
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/dataset/engine/iterators.py", line 144, in __next__
    data = self._get_next()
  File "/home/riemann/anaconda3/envs/luojianet/lib/python3.9/site-packages/luojianet_ms/dataset/engine/iterators.py", line 222, in _get_next
    return [self._transform_tensor(t) for t in self._iterator.GetNextAsList()]
RuntimeError: Unexpected error. Failed to open file: ./WHU-RS19/Parking/parking_28.jpg
Line of code : 277
File         : /home/vhr/tll/download/luojianet/luojianet_ms/ccsrc/minddata/dataset/core/tensor.cc

**Comment by ADHuan** [comment]
@sheke123

**Comment by sheke123** [comment]
从报错情况看，可能是图片读取的时候cpu进程设置有多个处理器，可以尝试减小num_workers数量或者设置为单线程模型。
